import { Charity } from "./charity_type";

export const demoCharities: Charity[] = [
  {
    id: '1',
    name: 'Hope Foundation',
    description: 'Providing education and healthcare to underprivileged children.',
    mission: 'Empower every child with equal opportunities.',
    logo: 'https://picsum.photos/id/100/200/200',
    banner: 'https://picsum.photos/id/101/1200/400',
    website: 'https://hopefoundation.org',
    email: 'contact@hopefoundation.org',
    phone: '+1 234 567 890',
    address: '123 Main St, New York, NY',
    verified: true,
    active: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Animal Rescue League',
    description: 'Saving stray animals and finding them loving homes.',
    mission: 'No animal left behind.',
    logo: 'https://picsum.photos/id/102/200/200',
    banner: 'https://picsum.photos/id/103/1200/400',
    website: 'https://animalrescue.org',
    email: 'info@animalrescue.org',
    phone: '+1 987 654 321',
    address: '456 Oak Ave, Los Angeles, CA',
    verified: false,
    active: true,
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Green Earth Initiative',
    description: 'Planting trees and fighting climate change.',
    mission: 'A sustainable future for all.',
    logo: 'https://picsum.photos/id/104/200/200',
    banner: 'https://picsum.photos/id/105/1200/400',
    website: 'https://greenearth.org',
    email: 'hello@greenearth.org',
    phone: '+1 555 123 456',
    address: '789 Pine St, Seattle, WA',
    verified: true,
    active: true,
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: '4',
    name: 'Water for All',
    description: 'Bringing clean drinking water to remote villages.',
    mission: 'Every drop counts – clean water as a human right.',
    logo: 'https://picsum.photos/id/106/200/200',
    banner: 'https://picsum.photos/id/107/1200/400',
    website: 'https://waterforall.org',
    email: 'support@waterforall.org',
    phone: '+1 555 987 6543',
    address: '321 River Rd, Denver, CO',
    verified: true,
    active: true,
    createdAt: '2024-04-05T00:00:00Z',
    updatedAt: '2024-04-05T00:00:00Z',
  },
  {
    id: '5',
    name: 'Mental Health Matters',
    description: 'Free counseling and crisis support for young adults.',
    mission: 'Break the stigma, heal the mind.',
    logo: 'https://picsum.photos/id/108/200/200',
    banner: 'https://picsum.photos/id/109/1200/400',
    website: 'https://mhmatters.org',
    email: 'care@mhmatters.org',
    phone: '+1 800 555 0199',
    address: '555 Wellness Blvd, Austin, TX',
    verified: false,
    active: true,
    createdAt: '2024-05-20T00:00:00Z',
    updatedAt: '2024-05-20T00:00:00Z',
  },
  {
    id: '6',
    name: 'Tech for Good',
    description: 'Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.Teaching coding and digital skills to underserved communities.',
    mission: 'Bridging the digital divide one line of code at a time.',
    logo: 'https://picsum.photos/id/110/200/200',
    banner: 'https://picsum.photos/id/111/1200/400',
    website: 'https://techforgood.org',
    email: 'hello@techforgood.org',
    phone: '+1 415 555 6789',
    address: '777 Innovation Way, San Francisco, CA',
    verified: true,
    active: true,
    createdAt: '2024-06-12T00:00:00Z',
    updatedAt: '2024-06-12T00:00:00Z',
  },
  {
    id: '7',
    name: 'Senior Care Alliance',
    description: 'Supporting isolated seniors with companionship and essentials.',
    mission: 'Dignity and joy for every elder.',
    logo: 'https://picsum.photos/id/112/200/200',
    banner: 'https://picsum.photos/id/113/1200/400',
    website: 'https://seniorcarealliance.org',
    email: 'help@seniorcarealliance.org',
    phone: '+1 888 555 4321',
    address: '101 Sunset Blvd, Miami, FL',
    verified: false,
    active: false,  // inactive charity example
    createdAt: '2024-07-01T00:00:00Z',
    updatedAt: '2024-07-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Arts for Everyone',
    description: 'Free art workshops and supplies for low-income youth.',
    mission: 'Creativity has no price tag.',
    logo: 'https://picsum.photos/id/114/200/200',
    banner: 'https://picsum.photos/id/115/1200/400',
    website: 'https://artsforeveryone.org',
    email: 'info@artsforeveryone.org',
    phone: '+1 312 555 7890',
    address: '202 Culture Ave, Chicago, IL',
    verified: true,
    active: true,
    createdAt: '2024-08-19T00:00:00Z',
    updatedAt: '2024-08-19T00:00:00Z',
  },
];